### ISSUE TITLE
Introduction and Prestudy should be possible to finalize before Mid-term delivery (final versions), except maybe table of definitions

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/orm#104]
Hvis alle er enig i at dette er godkjent trenger vi ikke gjøre flere endringer i innholdet i Del 1 og Del 2, rettskrivinger kan forekomme.
- [x] Kristian godkjenner
- [ ] Sebastian godkjenner
- [ ] Anders godkjenner
- [ ] Torgeir godkjenner
- [ ] Håvard godkjenner
- [x] Embrik godkjenner
- [ ] Carle godkjenner

**Comment by sardred** [comment]
We walked through this as a group, closed.
