### ISSUE TITLE
6 Tools

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/orm#127]
Are there more tools we have used that we should describe?
The goal of this issue is to finalize chapter 6.
- [x] Are we satisfied?
______
If not, go through and make the necessary changes:
Collaboration tools:
- [x] Go through description of tools
- [x] Go through why we choose the tools
Development tools:
- [x] Go through description of tools
- [x] Go through why we choose the tools
Frameworks and libraries:
- [x] Go through description of tools
- [x] Go through why we choose the tools

**Comment by Pontius1007** [comment]
Lest igjennom. Nestemann på lista må krysse av punktlisten om han er enig i kommentarer og egen retting.

**Comment by Sebba513** [comment]
Went through. Changed wording and grammar here and there. Added part about Django REST Framework.
