### ISSUE TITLE
As a user, I would like to see weather conditions that might influence (or have influenced) the road conditions.

### ISSUE THREAD

**Issue by sardred** [IT2901-24-2018/orm#4]
Yr.no or Mets API. Based on lat/long when dropping pin. Add filter to view or not view weather data on the map and/or roads

Sub Tasks
- [ ] Look through METs APIs and figure out what we want to use
- [ ] Update weather data when interacting with map
- [ ] Implement basic weather data when opening map

**Comment by Pontius1007** [comment]
https://api.met.no/weatherapi/locationforecast/1.9/documentation
