### ISSUE TITLE
Look through METs APIs and figure out what we want to use

### ISSUE THREAD

**Issue by sardred** [IT2901-24-2018/orm#64]
- [x] Yr vs. MET
- [x] MET has many APIs, what do we want to use?
- [x] Document on the wiki what we've determined
- [x] See if a component exist on the great interweebs. Leaflet component

**Comment by Goggman** [comment]
MET har bedre api/flere funksjoner

**Comment by Goggman** [comment]
No react component or leaflet extension sadly
