### ISSUE TITLE
Update wiki with info regarding sprint 1 and sprint planning meeting 2

### ISSUE THREAD

**Issue by sardred** [IT2901-24-2018/orm#70]
- [x] Results from sprint 1, no stories were finished
- [x] Results from sprint retrospective 1
- [x] Results from sprint planning meeting 2
- [x] Why did we change map? What is the data confusion? 
- [x] What did we do good? 
- [x] Matrix (?)

**Comment by Pontius1007** [comment]
Ser bra ut, men savner litt utdypende informasjon på hva som førte til at vi byttet kart og hva var grunnlaget for "data confusion"? Hvordan unngår vi det i fremtiden?

Mangler også hva vi gjorde positivt denne sprinten? Hva fikk vi til godt? 

Kan også vurdere en tiltaksmatrix om vi føler det er givende. Ta en titt på PP på BB. "Innspill til prosjektwiki".

**Comment by DjCreztian** [comment]
Sebastian/Carl-Erik kan skrive mer om data confusion? Antar det gjelder .geojson, de jobbet mest med denne.

**Comment by Pontius1007** [comment]
Looks good!
